INSERT INTO service_providers (
        provider_id,
        email,
        first_name,
        last_name,
        phone,
        business_name,
        bio,
        category,
        rating,
        city,
        state,
        postal_code,
        is_verified,
        created_at,
        updated_at
    )
VALUES (
        'provider_id:bigint',
        'email:varchar',
        'first_name:varchar',
        'last_name:varchar',
        'phone:varchar',
        'business_name:varchar',
        'bio:text',
        'category:varchar',
        'rating:decimal',
        'city:varchar',
        'state:varchar',
        'postal_code:varchar',
        'is_verified:tinyint',
        'created_at:timestamp',
        'updated_at:timestamp'
    );